if (typeof _dataid === "undefined" || _dataid === null || _dataid === "") { return false; } 
let loData = modelpanTopProperties.getData()._data;
let loConfig = modelpanTopProperties.getData()._config[loData.id];
let loResult = (loConfig?.overridesTitle || loConfig?.startsWizardStep);
let loCustomization = modelrendererCustomization.getData() ?? [];
if (!loCustomization.length) {return !!loResult;} // no customization, no renderer info
for (let name of Object.getOwnPropertyNames(loConfig?.useRenderer ?? {})) {
    if (loResult) {break;}
    loResult ||= !!(
        loConfig.useRenderer[name]
        && 
        loCustomization.find(
            custItem => 
                name === (custItem.composerId || `${custItem.nameSpace}--${custItem.displayType}`)
        )
    );
}
return !!loResult;
