const context = oEvent.oSource.getBindingContext();
currentObject = context.getObject();

const oper = [];

// Get VisibleField
const visibleField = controller.getObjectFromId(currentObject.visibleFieldName);

// Visibility
switch (visibleField.type) {
    case "MultipleChoice":
    case "MultipleSelect":
    case "CheckList":
        [
            FORMS.CONDITION_OPERATOR.CONTAINS_ANY,
            FORMS.CONDITION_OPERATOR.CONTAINS_ALL,
            FORMS.CONDITION_OPERATOR.EQUAL,
            FORMS.CONDITION_OPERATOR.NOT_EQUAL,
        ].forEach(operation => {
            const {key,title} = operation;
            oper.push({key,title})
        })
        break;

    case "SegmentedButton":
    case "SingleSelectIcon":
    case "SingleSelect":
    case "SingleChoice":
        [
            FORMS.CONDITION_OPERATOR.CONTAINS_ANY,
            FORMS.CONDITION_OPERATOR.EQUAL,
            FORMS.CONDITION_OPERATOR.NOT_EQUAL,
        ].forEach(operation => {
            const {key,title} = operation;
            oper.push({key,title})
        })
        break;

    case "CheckBox":
    case "Switch":
    case "Image":
    case "File":
        [
            FORMS.CONDITION_OPERATOR.EQUAL,
            FORMS.CONDITION_OPERATOR.NOT_EQUAL,
        ].forEach(operation => {
            const {key,title} = operation;
            oper.push({key,title})
        })
        break; 

    case "Numeric":
    case "Rating":
    case "StepInput":
        [
            FORMS.CONDITION_OPERATOR.GREATER_THAN,
            FORMS.CONDITION_OPERATOR.GREATER_OR_EQUAL,
            FORMS.CONDITION_OPERATOR.EQUAL,
            FORMS.CONDITION_OPERATOR.LOWER_OR_EQUAL,
            FORMS.CONDITION_OPERATOR.LOWER_THAN,
            FORMS.CONDITION_OPERATOR.NOT_EQUAL,
            FORMS.CONDITION_OPERATOR.BETWEEN,
            FORMS.CONDITION_OPERATOR.NOT_BETWEEN,
        ].forEach(operation => {
            const {key,title} = operation;
            oper.push({key,title})
        })
        break;

    case "TextArea":
        [
            FORMS.CONDITION_OPERATOR.EQUAL,
            FORMS.CONDITION_OPERATOR.NOT_EQUAL,
            FORMS.CONDITION_OPERATOR.STARTS_WITH,
            FORMS.CONDITION_OPERATOR.CONTAINS,
            FORMS.CONDITION_OPERATOR.ENDS_WITH,
        ].forEach(operation => {
            const {key,title} = operation;
            oper.push({key,title})
        })
        break;

    default:
        [
            FORMS.CONDITION_OPERATOR.GREATER_THAN,
            FORMS.CONDITION_OPERATOR.GREATER_OR_EQUAL,
            FORMS.CONDITION_OPERATOR.EQUAL,
            FORMS.CONDITION_OPERATOR.LOWER_OR_EQUAL,
            FORMS.CONDITION_OPERATOR.LOWER_THAN,
            FORMS.CONDITION_OPERATOR.NOT_EQUAL,
            FORMS.CONDITION_OPERATOR.STARTS_WITH,
            FORMS.CONDITION_OPERATOR.CONTAINS,
            FORMS.CONDITION_OPERATOR.ENDS_WITH,
        ].forEach(operation => {
            const {key,title} = operation;
            oper.push({key,title})
        })
        break;
}

modellistVisibilityOperation.setData(oper);

popVisibilityOperation.openBy(this);
