if (typeof visibleFieldName === "undefined" || visibleFieldName === null || visibleFieldName === "") { return false; }  

const object = controller.getObjectFromId(visibleFieldName);
if (!object) return false;

switch (object.type) {
    case "Numeric":
    case "Rating":
    case "StepInput":
    case "Calc": // #70 - 2.2.
    case "AngleCalc": // #70 - 2.2.
        switch(visibleCondition) {
            case FORMS.CONDITION_OPERATOR.BETWEEN.key:
            case FORMS.CONDITION_OPERATOR.NOT_BETWEEN.key:
                return true;
            default:
                return false;
        }
    default:
        return false;
}
