if (typeof visibleFieldName === "undefined" || visibleFieldName === null || visibleFieldName === "") { return false; }  

const object = controller.getObjectFromId(visibleFieldName);
if (!object) return false;

switch (object.type) {
    case "MultipleChoice":
    case "MultipleSelect":
    case "SegmentedButton":
    case "SingleSelectIcon":
    case "SingleSelect":
    case "SingleChoice":
    case "CheckList":
    case "CheckBox":
    case "Switch":
    case "Image":
    case "File":
        return false;
    case "Numeric":
    case "Rating":
    case "StepInput":
        switch(visibleCondition) {
            case FORMS.CONDITION_OPERATOR.BETWEEN.key:
            case FORMS.CONDITION_OPERATOR.NOT_BETWEEN.key:
                return false;
            default:
                return true;
        }
    default:
        return true;
}
