var binding = tabApps.getBinding("items");

var filters = [];

filters.push(new sap.ui.model.Filter({
    filters: [
        new sap.ui.model.Filter("name", "Contains", this.getValue()),
        new sap.ui.model.Filter("changedBy", "Contains", this.getValue()),
        new sap.ui.model.Filter("description", "Contains", this.getValue()),
        new sap.ui.model.Filter("application", "Contains", this.getValue()),
    ],
    and: false
}));

if (toolAppsUser.getSelectedKey() === "Mine") filters.push(new sap.ui.model.Filter("changedBy", "EQ", systemSettings.user.username))

$.each(toolAppsPackage.getSelectedKeys(), function (i, key) {
    filters.push(new sap.ui.model.Filter("package", "EQ", key));
});

binding.filter(filters);

oPageAppsNumber.setUnit("(" + binding.getLength() + ")");
